### ISSUE TITLE
Wrong activity tracker

### ISSUE THREAD

**Issue by Thogort** [HanSolo/digital#2]
The calories shown when only activity calories are selected are not the same as in Garmin Connect.
When i uncheck this option the summary calories are the same. Only activity seems a problem. Seems a problem since Firmware 5.20

Btw. ain´t it possible to change the am/pm to the left side and seconds on the right? With seconds i will obey this watchface.

**Comment by HanSolo** [comment]
Yep, I saw the same effect, it seems that Garmin changed the algorithm that they use to calculate the active calories.
Will try to figure out a solution, thanx for the report.

**Comment by Thogort** [comment]
wrrhw aaaaahnr aguhwwgggghhh uughghhhgh huuguughghg huuguughghg huuguughghg aarrragghuuhw huuguughghg 

Wookie Translation: and have you thought about the option to add seconds?

**Comment by HanSolo** [comment]
It's not possible to show seconds in custom watchfaces because they only update once per minute per default :(

**Comment by Thogort** [comment]
Maybe i understand not really the logic. But ain´t it possible to use the light on function when you rotate your wrist to update also? Other watchfaces work with that and the seconds diasappear after 10s. If you rotate your wrist again the will show up.
Would be great. I love this watchface. Great work.

**Comment by HanSolo** [comment]
So I've checked several things and it seems that the burned calories that I get from the ConnectIQ SDK are around 20% higher than before. I calculate the base calories by using the Mifflin-St.Jeor formular. In principle I simply subtract the calculated base calories from the total burned calories which should give me the active calories. This worked very fine until 5.2 and because I did not change anything I guess that the total burned calories calculation in 5.2 is higher than in 4.7.
In the 2.1.0 SDK there is a new feature which is activeMinutesDay which I could use for calculation but this is not available in 1.2.11 :(

**Comment by Thogort** [comment]
Today is a very lazy office day. Only meetings. Until yet the watchface says im having 403kcal activity and Connect says 179. That´s ~125% difference.
Also i had yesterday a cycling tour with 85km and not using the app. So just worn the watch. Connect said i had 3500kcl activity and the watchface says im havening 7200kcal. Damnit 3 more days and im dead :-)

**Comment by HanSolo** [comment]
That's really strange...I saw on the FR235 forum that there are more people having problems with the calorie calculation with 5.2.
Somehow the total burned calorie value that I get from the SDK seems to be too high...will further investigate...

**Comment by HanSolo** [comment]
I just saw that the calories at rest increased from 1741 to 2130 in my calorie details. Means with 5.2 the base calorie calculation seems to be different than before. My own calculation is around 1745 which explains the difference in calculation. Just don't know how they calculate 2130 as calories at rest...

**Comment by HanSolo** [comment]
Ok, I've contacted Garmin and they confirmed that all Forerunners now calculate the calories at rest by using BMR + 20% which is exactly what I've found out.
Will prepare a new version asap.

**Comment by Thogort** [comment]
Won´t work correct with Firmware 5.20 Same Problem with wrong activity calories.
But now is Firmware 5.40 out and it is not possible now to activate your watchface. Also the update won´t work. It will sync and the update is shown everytime in open the settings. 
I uninstallesd it and loaded the new version and now the update button is gone. But not possible to acitvate this watchface. Not via connect and not via watch. Only original watch from Garmin is shown. All other watchfaces work.

**Comment by HanSolo** [comment]
Yep I see the same problem on my watch...damn it. I'm currently creating a copy of the whole watch face named Digital2 and hope that the name thing was the problem.

**Comment by HanSolo** [comment]
Hmm...tried different names but still have the same problem...I have no idea how to fix that :(

**Comment by HanSolo** [comment]
Ok, I've found the problem and I've tried to fix it. On my watch I still see problems with the steps but in the Simulator it works perfectly fine. Will wait until tomorrow and check if with starting a new day it will get better.

**Comment by HanSolo** [comment]
Ok, it seems with the latest modifications the values are correct again. The BMR correction factor is now 0.21385 instead of 0.2. This gives me the exact same values that I see in the mobile Connect app for active calories.

**Comment by Thogort** [comment]
Nice work. Connect and watch are close together. 53 watch and 42 connect.
Also seconds are avaiable. 
I will have a look on it if calories stay close.

**Comment by HanSolo** [comment]
Just came back from a 10 km run and the active calories have been nearly exactly the same as in the app. If the difference is bigger on your watch it might be that Garmin takes the age into account. So maybe the BMR correction factor is age dependent but I was not able to figure that out. Would you mind sending me some data to make a calculation? I would need gender, age, weight and height. In addition I would need the rest calories from the Garmin Connect application. With this data it might be possible to calculate an age dependent correction factor (only if you are not 46 like I am ;) ).
You could send the data also to my mail address so that it doesn't appear here, it is han.solo.gg@gmail.com
